export const jobsData = [
  {
    companyName: "BostonGene Technologies",
    jobName: "Junior Frontend Developer",
    photoUrl:
      "https://681828296218-prod-staff.s3.eu-central-1.amazonaws.com/staff.am/upload/2/8/8/9/28891283.png",
    JobDescription:
      "BostonGene is a pioneer company that uses biomedical software to identify new and personalized treatment options with next-generation multi-platform analytics, improving and optimizing cancer patient outcomes. We develop a distributed information and analytical system that provides oncologists with the necessary data for diagnosis and personalized treatment of patients.",
    jobCategory: "Software development",
    RequiredCandidateLevel: "Junior",
    location: "Yerevan",
    ProfessionalSkills: ["JavaScript", "React.js", "Redux", "TypeScript"],
    Requiredqualifications: [
      "Knowledge of C# and SQL.",
      "English communication skills.",
      "Work collaboratively with a team.",
    ],
    Additionalinformation: "",
  },
  {
    companyName: "DPD in Armenia",
    jobName: "Customer Service Agent",
    photoUrl:
      "https://681828296218-prod-staff.s3.eu-central-1.amazonaws.com/staff.am/upload/a/9/c/a/a9ca88e8.png",
    JobDescription:
      "DPD in Armenia (“Evrazes Express” LLC) is looking for a skilled, enthusiastic and competent specialist for the position of Customer Service Agent who will represent front line of the company.",
    jobCategory: "Sales/service management",
    RequiredCandidateLevel: "Junior",
    location: "Yerevan",
    ProfessionalSkills: ["Advising clients by phone"],
    Requiredqualifications: [
      "Knowledge of C# and SQL.",
      "English communication skills.",
      "Work collaboratively with a team.",
    ],
    Additionalinformation: "",
  },
  {
    companyName: "BostonGene Technologies",
    jobName: "Junior Frontend Developer",
    photoUrl:
      "https://681828296218-prod-staff.s3.eu-central-1.amazonaws.com/staff.am/upload/2/8/8/9/28891283.png",
    JobDescription:
      "BostonGene is a pioneer company that uses biomedical software to identify new and personalized treatment options with next-generation multi-platform analytics, improving and optimizing cancer patient outcomes. We develop a distributed information and analytical system that provides oncologists with the necessary data for diagnosis and personalized treatment of patients.",
    jobCategory: "Software development",
    RequiredCandidateLevel: "Junior",
    location: "Yerevan",
    ProfessionalSkills: ["JavaScript", "React.js", "Redux", "TypeScript"],
    Requiredqualifications: [
      "Knowledge of C# and SQL.",
      "English communication skills.",
      "Work collaboratively with a team.",
    ],
    Additionalinformation: "",
  },
  {
    companyName: "BostonGene Technologies",
    jobName: "Junior Frontend Developer",
    deadline: " 21 January 2023",
    photoUrl:
      "https://681828296218-prod-staff.s3.eu-central-1.amazonaws.com/staff.am/upload/2/8/8/9/28891283.png",
    JobDescription:
      "BostonGene is a pioneer company that uses biomedical software to identify new and personalized treatment options with next-generation multi-platform analytics, improving and optimizing cancer patient outcomes. We develop a distributed information and analytical system that provides oncologists with the necessary data for diagnosis and personalized treatment of patients.",
    jobCategory: "Software development",
    jobType: "Full time",
    requiredCandidateLevel: "Junior",
    location: "Yerevan",
    professionalSkills: ["JavaScript", "React.js", "Redux", "TypeScript"],
    softSkills: [
      "Ability to work independently",
      "Positive attitude",
      "Teamwork",
    ],
    requiredqualifications: [
      "Recent graduate or a last year student;",
      "Computer Science degree or related degree;",
      "up to 1 year in Software Engineering using React, being familiar with Redux is a plus;",
      "good knowledge of HTML basics and CSS fundamentals, we use SCSS;",
      "good knowledge of JavaScript, will be nice to have some idea of TypeScript basics;",

      "will be great if you are familiar with Node.js (just a little bit will be fine);",
      "you have to have heard something about testing your code;",
    ],
    additionalinformation: [
      "ull-time position, permanent contract, flexible working hours, hybrid work (office in the center of Yerevan);",
      "versatile professional environment: bioinformatics, biologists, physicians, and software developers who united to save people’s lives;",
      "frequent performance reviews;",
      "competitive salary and healthcare insurance, on-site catering.",
    ],
  },
  {
    companyName: "DPD in Armenia",
    jobName: "Customer Service Agent",
    photoUrl:
      "https://681828296218-prod-staff.s3.eu-central-1.amazonaws.com/staff.am/upload/a/9/c/a/a9ca88e8.png",
    JobDescription:
      "DPD in Armenia (“Evrazes Express” LLC) is looking for a skilled, enthusiastic and competent specialist for the position of Customer Service Agent who will represent front line of the company.",
    jobCategory: "Sales/service management",
    requiredCandidateLevel: "Junior",
    location: "Yerevan",
    professionalSkills: ["Advising clients by phone"],
    requiredqualifications: [
      "Knowledge of C# and SQL.",
      "English communication skills.",
      "Work collaboratively with a team.",
    ],
    additionalinformation: "",
  },
];

let b = [
  "Software development",
  "Quality Assurance /Control",
  " UI/UX/Graphic Design",
  " Product/Project Management",
  "Hardware design",
  "Other IT",
  "Sales/service management",
  "Administrative/office-work",
  "Tourism/Hospitality/HoReCa",
  "Marketing/Advertising",
  "Communications/Journalism/PR",
  " Accounting/Bookkeeping/Cash register",
  " Finance Management",
  "Banking/credit",
  "TV/Radio",
  "Education/training",
  " Legal",
  " Audit/Compliance",
  "Healthcare/Pharmaceuticalt",
  "Construction",
  "Human Resources",
  "Sports/Beauty",
  "Procurement/Logistics/Courier",
  "Production/Bookkeeping/Cash register",
  "Business/Management",
  "Art/Design/Architecture",
  " General/professional/Other services",
  "IT security/Networks",
  " NGO/Nonprofit",
  "Insurance",
  "Entertainment",
  "Data Science/Data Engineering",
  " Foreign language",
  "Hardware Design",
  " Data Research/Analysis",
  " Mechanical/Engineering",
  "System Admin/Engineer",
  " Network Administratio",
  "Consultancys",
  "State/ Public/ Civil servic",
  "Science",
  "Content writing",
  "Security",
  "DevOps/Infrastructure",
  "IT Support/Technician",
];
